### ISSUE TITLE
Feedback from Donglin

### ISSUE THREAD

**Issue by DonglinLiu** [teokem/project-work-2021-maximisu90#2]
Thank you for the interesting project!  Here is some comments that may helpful for the project:

- [x] It's better to have an abstract on README.md for the whole project.
- [x] The binder is working very well, but maybe mention it in README.md would be clearer
- [x] For some figures, it may clearer to plot in two columns as comparison rather than separate them. For instance some figures in electron beams with chirp and without chirp.
- [x] Saving the figures to the disk.

Anyway, nice work! I really learned a lot from the nice plots.

**Comment by maximisu90** [comment]
Thank you for your comments I have implemented some changes and I hope it is better now
