### ISSUE TITLE
Late Reveiw

### ISSUE THREAD

**Issue by exook** [teokem/project-work-2021-maximisu90#3]
Dear Maximisu90,

I wrote these comments late April, but since I cannot find them here I must have messed up the submission. Of course I don't expect you to implement my comments since they are arriving so late. But please look at what I wrote regarding section headers at the bottom of this message, I think this could really benefit your notebook work in the future.

Best regards,
Alex

# From Checklist
- [x] Documentation:
- [x] title and abstract of the project (max 300 words)
- [x] includes instructions on how to run the notebook
- [x] includes the required packages in an `environment.yml` file
- [ ] includes a brief explanation of the reason each package/library was used
* There is no explanation to why certain packages are included. scipy, sympy, openpyxl, ipywidgets, seaborn, and pip, seem to be included without being used
- [x] includes rich documentation using Markdown (equations, tables, links, images or videos)
- [x] is reproducible, _i.e._, someone else should be able to redo the steps
- [x] Input/Output:
- [x] uses `pandas` to read large data sets or `numpy` to load data from text files
- [x] uses `pandas` to save to disk the processed or generated data
- [x] Scientific computing/data processing:
- [x] performs numerical operations (`numpy`, `scipy`, `pandas`) or manipulates, groups, and aggregates a data set (`pandas`)
- [x] Data visualization:
- [x] includes at least one composite plot (inset or multiple panels)
- [x] produces _publication ready_ quality figures (see [here](http://dx.doi.org/10/cg2g) for an editorial guide on _Graphical Excellence_):
- [ ] the figures are 89 mm wide (single column) or 183 mm wide (double column)
* I cannot verify that they are 89 or 183 mm
- [x] the axes are labeled
- [x] the font sizes are sufficiently large
- [x] the figures are saved as rasterized images (300 dpi) or vector art
* Saved as PNG
- [x] Version control, sharing, and archiving:
- [x] is archived in a repository with a digital object identifier (DOI)
## General
* Very nice, article-like, structure of the notebook. I have seen that it is possible to generate a table of contents, but I didn't have the motivation to do it myself.
* Most of the text is written as 3rd order text header (### Text), I would suggest to use normal text. This would remove the need to mark paragraph headings with ">". Instead of 
~~~
## > The Undulator ### An undulator is a periodic magnetic array` I would use 
~~~
I would use
~~~
## The Undulator
An undulator is a periodic magnetic array`
~~~
* There are some typos and grammatical errors in the abstract, for example "Free electron letters (FELs)". I would suggest to copy/paste each text cell individually into a spell checker, and then pasting them back into the notebook
* The notebook has a great combination of well written text and exceptional figures to make the topic and procedure easy to understand.
* Adding more comments in the code and not only relying on the text cells would make this notebook even easier to follow

**Comment by maximisu90** [comment]
**includes a brief explanation of the reason each package/library was used

    There is no explanation to why certain packages are included. scipy, sympy, openpyxl, ipywidgets, seaborn, and pip, seem to be included without being used**

I have removed the unused packages and added comments to the ones I use


 **produces publication ready quality figures (see here for an editorial guide on Graphical Excellence):

    the figures are 89 mm wide (single column) or 183 mm wide (double column)

    I cannot verify that they are 89 or 183 mm**
In the mplstyle file I set the size of the figures however I set them to twice the 89 mm to make the fine features in the scatter plots more visible


I have corrected the spelling errors and changed the markdown text to include less ### text.
